### ISSUE TITLE
DCA error 

### ISSUE THREAD

**Issue by cnk113** [Zhangxf-ccnu/EnImpute#1]
Hello,

I'm running into issues with running DCA when it's trying to save the latent representation.
```Error in count.imputed.individual[, , k] <- DCA.EnImpute(count, normtype = DCA.normtype,  : number of items to replace is not a multiple of replacement length ```

Thanks

**Comment by Zhangxf-ccnu** [comment]
Hi Kim,

    EnImpute depends on the Python package, dca (https://github.com/theislab/dca). Before installing and running EnImpute, please install dca  following the corresponding readme file (It may be required to set path environment variables), and check whether it can be run from the command line. Thanks!

xiaofei

**Comment by cnk113** [comment]
Actually I figured out the issue, if you have duplicate barcodes from different runs the read.table in DCA will throw an error so you have to accept rownames as NULL and shift the columns. Also I've noticed the tool takes a long time, is it possible to run all the tools in parallel?
